<?php
/**
 * integer_net Magento Module
 *
 * @category IntegerNet
 * @package IntegerNet_Piwik
 * @copyright  Copyright (c) 2012-2013 integer_net GmbH (http://www.integer-net.de/)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 * @author Viktor Franz <vf@integer-net.de>
 */

/**
 * Enter description here ...
 */
?>

<?php /** @var $this IntegerNet_Piwik_Block_Track */ ?>

<?php if(!Mage::helper('integernet_piwik')->isHeadJs()): ?>
    <script type="text/javascript" defer="" async="" src="<?php echo $this->getPiwikJsSrc() ?>"></script>
<?php endif; ?>

<script type="text/javascript">
    var _paq = _paq || [];

    _paq.push(["setTrackerUrl", "<?php echo $this->getPiwikPhpSrc() ?>"]);
    _paq.push(["setSiteId", "<?php echo $this->getSideId() ?>"]);
    _paq.push(["enableLinkTracking"]);

    <?php if($_search = $this->searchArguments()) : ?>
        _paq.push(["trackSiteSearch", <?php echo $_search ?>]);
    <?php endif; ?>

    <?php if($_arguments = $this->getCatalogViewArguments()) : ?>
        _paq.push(["setEcommerceView", <?php echo $_arguments ?>]);
    <?php endif; ?>

    <?php if($_arguments = $this->getProductViewArguments()) : ?>
        _paq.push(["setEcommerceView", <?php echo $_arguments ?>]);
    <?php endif; ?>

    <?php if($_argumentsList = $this->getCartItemArguments()) : ?>
        <?php foreach($_argumentsList as $_arguments) : ?>
            _paq.push(["addEcommerceItem", <?php echo $_arguments ?>]);
        <?php endforeach; ?>
    <?php endif; ?>

    <?php $_arguments = $this->getCartArguments() ?>
    <?php if($_arguments !== null) : ?>
        _paq.push(["trackEcommerceCartUpdate", <?php echo $_arguments ?>]);
    <?php endif; ?>

    <?php if($_argumentsList = $this->getOrderItemArguments()) : ?>
        <?php foreach($_argumentsList as $_arguments) : ?>
            _paq.push(["addEcommerceItem", <?php echo $_arguments ?>]);
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if($_arguments = $this->getOrderArguments()) : ?>
        _paq.push(["trackEcommerceOrder", <?php echo $_arguments ?>]);
    <?php endif; ?>

    _paq.push(["trackPageView"]);

    <?php if($this->getTrackOnepageSteps()): ?>
        Ajax.Responders.register({
            onCreate: function(response) {
                if(response.url) {
                    var saveMethod = response.url.match(/(save\w*)/);
                    if(saveMethod && saveMethod.length) {
                        _paq.push(["trackPageView", saveMethod[0]]);
                    }
                }
            }
        });
    <?php endif; ?>

</script>

<noscript>
    <img src="<?php echo sprintf('%s?idsite=%s&rec=1', $this->getPiwikPhpSrc(), $this->getSideId())?>" style="border:0" alt="" />
</noscript>








